# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build logic apps application and deploy it to multiple optional environments
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV'] # or ['DEV','QA'] or ['DEV','QA','PROD'] or ['DEV','QA','STG','PROD']
- name: variableGroupName
  default: 'myVariableGroupName'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/build-container-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'