name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: "ubuntu-latest"

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "Infrastructure/**/*.yml"
      - "Infrastructure/**/*.bicep"

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environment
    displayName: Variable Group
    type: string
    default: LogicAppDemo-Dev
    values:
      - LogicAppDemo-Dev
      - LogicAppDemo-QA
  # - name: servicePrincipalName
  #   type: string
  #   displayName: Service Principal Name
  #   default: WebAppMVP
  - name: resourceGroupName
    type: string
    displayName: Resource Group Name
    default: ""

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: CreateInfrastructure
    variables:
      - group: ${{ parameters.environment }}
    displayName: "Create Infrastructure ${{ parameters.environment }}"
    jobs:
      - template: templates/create-infra-template.yml
        parameters:
          variableGroupName: ${{ parameters.environment }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          # servicePrincipalName: ${{ parameters.servicePrincipalName }}
          # environmentName: $(envTag)
