# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Logic Application to existing Function App
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: "ubuntu-latest"

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Workflows/*

variables:
  devVariableGroup: "LogicAppDemo-Dev"
  devEnvName: "dev"
  qaVariableGroup: "LogicAppDemo-QA"
  qaEnvName: "qa"

# ----------------------------------------------------------------------------------------------------

stages:
  - stage: BuildDev
    variables:
      - group: ${{ variables.devVariableGroup }}
    displayName: "Build Dev"
    jobs:
      - template: templates/build-logicstd-template.yml
        parameters:
          variableGroupName: ${{ variables.devVariableGroup }}
          environmentName: ${{ variables.devEnvName }}

  - stage: DeployDev
    variables:
      - group: ${{ variables.devVariableGroup }}
    displayName: "Deploy Dev"
    jobs:
      - template: templates/deploy-logicstd-template.yml
        parameters:
          variableGroupName: ${{ variables.devVariableGroup }}
          environmentName: ${{ variables.devEnvName }}

  # ----------------------------------------------------------------------------------------------------

  - stage: BuildQa
    variables:
      - group: ${{ variables.qaVariableGroup }}
    displayName: "Build QA"
    jobs:
      - template: templates/build-logicstd-template.yml
        parameters:
          variableGroupName: ${{ variables.qaVariableGroup }}
          environmentName: ${{ variables.qaEnvName }}

  - stage: DeployQa
    variables:
      - group: ${{ variables.qaVariableGroup }}
    displayName: "Deploy QA"
    jobs:
      - template: templates/deploy-logicstd-template.yml
        parameters:
          variableGroupName: ${{ variables.qaVariableGroup }}
          environmentName: ${{ variables.qaEnvName }}
