# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: variableGroupName
    default: ""
  # - name: environmentName
  #   default: 'DEV'
  # - name: servicePrincipalName
  #   default: ""
  - name: resourceGroupName
    default: ""
  - name: templateFolderName
    default: "Infrastructure/bicep"
  - name: templateFileName
    default: "main.bicep"

# ----------------------------------------------------------------------------------------------------
jobs:
  - deployment: CreateInfra
    displayName: Initialize Create Infra
    environment: $(envTag)

  - job: CreateInfraJob
    displayName: Create Infrastructure
    variables:
      - group: ${{ parameters.variableGroupName }}
      # - name: environmentNameUpper
      #   value: $[upper(envTag)]
      # - name: environmentNameLower
      #   value: $[lower(envTag)]
      - name: templateFile
        value: "$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}"
      # - name: resourceGroupSuffixBase
      #   value: '_$[lower(envTag)]'
      # - name: resourceGroupSuffix
      #   value: ${{ replace(variables.resourceGroupSuffixBase, '_prod', '') }}

          # resourceGroupName=$(echo "$(appPrefix)-$(longAppName)-$(envTag)" | tr '[:upper:]' '[:lower:]')
          #           resourceGroupName=${{ parameters.resourceGroupName }}
          # echo "resourceGroupName=$resourceGroupName"
          # echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"
    steps:
      - bash: |
          appPrefixLower=$(echo "$(appPrefix)" | tr '[:upper:]' '[:lower:]')
          echo "##vso[task.setvariable variable=appPrefixLower]$appPrefixLower"



          runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
          echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
          echo "runDateTime=$runDateTime"
        displayName: "Create Variables"

      - bash: |
          # echo "environmentNameUpper=$(environmentNameUpper)"
          # echo "environmentNameLower=$(environmentNameLower)"
          echo "resourceGroupSuffixBase=$(resourceGroupSuffixBase)"
          echo "resourceGroupSuffix=$(resourceGroupSuffix)"
          echo "resourceGroupName=${{ parameters.resourceGroupName }}"
          echo "azureSubscription=$(azureSubscription)"
          echo "region=$(region)"
          echo "orgPrefix=$(orgPrefix)"
          echo "appPrefix=$(appPrefix)"
          echo "appPrefixLower=$(appPrefixLower)"
          echo "templateFile=$(templateFile)"
          tree $(Pipeline.Workspace)
        displayName: "Display Variables"
        continueOnError: true

      - task: AzureCLI@2
        displayName: "Create Resource Group"
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az group create --name ${{ parameters.resourceGroupName }} --location $(region) --tags LastDeployed=$(runDateTime) Organization=$(orgPrefix) Application=$(appPrefix) # Environment=$(environmentNameUpper)

      # add service principal as owner to resource group
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines&viewFallbackFrom=azure-devops#task-inputs

      # - pwsh: |
      #     $principalId=$(az ad sp list --filter "displayName eq '${{ parameters.variableGroupName }}'" --query '[].id' -o tsv)
      #     Write-Host $principalId
      #     az role assignment create --assignee $($principalId) --role "Owner" --resource-group $($resourceGroupName)
      #   displayName: "Add SP to RG"
      #   continueOnError: false
      
      # - task: AzureCLI@2
      #   displayName: "Add SP to RG"
      #   inputs:
      #     azureSubscription: $(azureSubscription)
      #     scriptType: pscore
      #     scriptLocation: inlineScript
      #     inlineScript: |
      #       Write-Host ${{ parameters.servicePrincipalName }}
      #       $principalId=$(az ad sp list --filter "displayName eq '${{ parameters.servicePrincipalName }}'" --query '[].id' -o tsv)
      #       Write-Host $principalId
      #       az role assignment create --assignee $($principalId) --role "Owner" --resource-group ${{ parameters.resourceGroupName }}

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: "Publish Bicep Resources"
        inputs:
          csmFile: $(templateFile)
          overrideParameters: >
            -appPrefix $(appPrefix) 
            -environment $(envTag)
            -longAppName $(longAppName)
            -shortAppName $(shortAppName)
          deploymentScope: "Resource Group"
          azureResourceManagerConnection: $(azureSubscription)
          action: "Create Or Update Resource Group"
          resourceGroupName: "${{ parameters.resourceGroupName }}"
          location: "$(region)"
          templateLocation: "Linked artifact"
          deploymentMode: "Incremental"
