# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: "ubuntu-latest"

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "Infrastructure/**/*.yml"
      - "Infrastructure/**/*.bicep"

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environment
    displayName: Variable Group
    type: string
    default: LogicAppDemo-Dev
    values:
      - LogicAppDemo-Dev
      - LogicAppDemo-QA

# ----------------------------------------------------------------------------------------------------
stages:
  - stage:
    variables:
      - group: ${{ parameters.environment }}
    jobs:
      - job:
        steps:
          - template: pipes/infra-only-pipeline-template.yml
            parameters:
              variableGroupName: ${{ parameters.environment }}
              environments: ["$(envTag)"] # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
