# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Logic Application to existing Function App
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: "ubuntu-latest"

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Workflows/*

# ----------------------------------------------------------------------------------------------------
# stages:
# - template: pipes/logicstd-only-pipeline-template.yml
#   parameters:
#     variableGroupName: 'LogicAppDemo'
#     environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']

stages:
  - stage:
      - template: pipes/logicstd-only-pipeline-template.yml
        parameters:
          variableGroupName: "LogicAppDemo-Dev"
          environments: ["dev"] # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']

  - stage:
      - template: pipes/logicstd-only-pipeline-template.yml
        parameters:
          variableGroupName: "LogicAppDemo-QA"
          environments: ["qa"] # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']

